''' Demo site generator'''
# Relative imports python
import sys
sys.path.append(".") 

from time import sleep
from sitegenerator import SiteGenerator
from datetime import datetime
import json

# Demo blog post data
demo_data = [
    {
        "id": 1,
        "title": "Demo.py",
        "text": "This page is generated by the 'demo.py'-script."},
    {
        "id": 2,
        "title": "Code",
        "text": "The code for this demo can be found in the ./demo folder. For more details visit the Github page."
    }
]

# Generate small markup files to use in the main template. 
for data in demo_data:
    post = SiteGenerator()
    post.template_folder = "./demo/templates"
    post.base_template = "base_posts.html"
    post.output_file = "./demo/templates/post_" + str(data["id"]) + ".html"
    post.replacements = {
        "title": data["title"],
        "text": data["text"],
    }
    post.render()


# Update main template with new templates
indexpage = SiteGenerator(output_file="./docs/index.html")
indexpage.template_folder = "./demo/templates"
indexpage.render()
